version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  deploy:
    docker:
      - image: 'circleci/python:2.7'
    working_directory: /tmp/hackersuse
    steps:
      - checkout
      - aws-s3/sync:
          from: /tmp/hackersuse
          to: s3://hackersuse.com
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
          overwrite: true

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master